language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - hhvm

branches:
  only:
    - master
    - dev

before_script:
  - curl -s https://getcomposer.org/installer | php
  - $(which php) composer.phar --dev --no-progress --no-interaction install

script:
  - bin/phpunit
  - bin/phpspec run --format=pretty
